name: salone_bazaar
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  component_library:
    path: ./packages/component_library
  bazaar_api:
    path: ./packages/bazaar_api
  sign_in:
    path: ./packages/features/sign_in
  sign_up:
    path: ./packages/features/sign_up
  go_router: ^14.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
